apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: enterprise-metrics-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enterprise-metrics-role
subjects:
- kind: ServiceAccount
  name: enterprise-metrics
  namespace: system
